CREATE TABLE IF NOT EXISTS pipeline_step (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id VARCHAR(120) NOT NULL,
    task_type VARCHAR(120) NOT NULL,
    status VARCHAR(40) NOT NULL,
    artifact_ref VARCHAR(255),
    payload_json CLOB,
    idempotency_key VARCHAR(200) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_pipeline_step_job_task ON pipeline_step(job_id, task_type);
CREATE UNIQUE INDEX IF NOT EXISTS uk_pipeline_step_idempotency ON pipeline_step(idempotency_key);
