CREATE TABLE IF NOT EXISTS validation_artifact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id VARCHAR(120) NOT NULL,
    task_type VARCHAR(120) NOT NULL,
    validation_json CLOB NOT NULL,
    validation_status VARCHAR(16) NOT NULL,
    violation_count INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_validation_artifact_job_task ON validation_artifact(job_id, task_type);
